apiVersion: apps/v1
kind: Deployment
metadata:
  name: gztrdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gztrdu
  template:
    metadata:
      labels:
        app: gztrdu
    spec:
      containers:
      - image: okteto.dev/gztrdu:latest
        name: gztrdu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "872ca7df-2ebe-4eca-b009-0520f38b1bcd"
        - name: Vless_Path
          value: "/vl66uhtiui"
        - name: Vmess_UUID
          value: "872ca7df-2ebe-4eca-b009-0520f38b1bcd"
        - name: Vmess_Path
          value: "/vmu77tgk"
        - name: Share_Path
          value: "/v2link"
